// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access_requests.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveAccessRequest = `-- name: ApproveAccessRequest :one
UPDATE access_requests
SET status = 'approved',
    magic_token_hash = $2,
    magic_expires_at = $3,
    magic_used_at = NULL,
    decided_at = NOW(),
    decided_by = $4
WHERE id = $1 AND status IN ('pending', 'approved', 'denied')
RETURNING id, name, email, reason, status, magic_token_hash, magic_expires_at, magic_used_at, session_hash, session_expires_at, ip, user_agent, telegram_msg_id, created_at, decided_at, decided_by
`

type ApproveAccessRequestParams struct {
	ID             uuid.UUID          `json:"id"`
	MagicTokenHash *string            `json:"magic_token_hash"`
	MagicExpiresAt pgtype.Timestamptz `json:"magic_expires_at"`
	DecidedBy      *string            `json:"decided_by"`
}

func (q *Queries) ApproveAccessRequest(ctx context.Context, arg ApproveAccessRequestParams) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, approveAccessRequest,
		arg.ID,
		arg.MagicTokenHash,
		arg.MagicExpiresAt,
		arg.DecidedBy,
	)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Reason,
		&i.Status,
		&i.MagicTokenHash,
		&i.MagicExpiresAt,
		&i.MagicUsedAt,
		&i.SessionHash,
		&i.SessionExpiresAt,
		&i.Ip,
		&i.UserAgent,
		&i.TelegramMsgID,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
	)
	return i, err
}

const clearSessionByHash = `-- name: ClearSessionByHash :exec
UPDATE access_requests SET session_hash = NULL, session_expires_at = NULL
WHERE session_hash = $1
`

func (q *Queries) ClearSessionByHash(ctx context.Context, sessionHash *string) error {
	_, err := q.db.Exec(ctx, clearSessionByHash, sessionHash)
	return err
}

const consumeMagicAndCreateSession = `-- name: ConsumeMagicAndCreateSession :one
UPDATE access_requests
SET magic_used_at = NOW(),
    session_hash = $2,
    session_expires_at = $3
WHERE id = $1
RETURNING id, name, email, reason, status, magic_token_hash, magic_expires_at, magic_used_at, session_hash, session_expires_at, ip, user_agent, telegram_msg_id, created_at, decided_at, decided_by
`

type ConsumeMagicAndCreateSessionParams struct {
	ID               uuid.UUID          `json:"id"`
	SessionHash      *string            `json:"session_hash"`
	SessionExpiresAt pgtype.Timestamptz `json:"session_expires_at"`
}

func (q *Queries) ConsumeMagicAndCreateSession(ctx context.Context, arg ConsumeMagicAndCreateSessionParams) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, consumeMagicAndCreateSession, arg.ID, arg.SessionHash, arg.SessionExpiresAt)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Reason,
		&i.Status,
		&i.MagicTokenHash,
		&i.MagicExpiresAt,
		&i.MagicUsedAt,
		&i.SessionHash,
		&i.SessionExpiresAt,
		&i.Ip,
		&i.UserAgent,
		&i.TelegramMsgID,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
	)
	return i, err
}

const countRecentRequestsByIP = `-- name: CountRecentRequestsByIP :one
SELECT COUNT(*) FROM access_requests
WHERE ip = $1 AND created_at > NOW() - ($2::interval)
`

type CountRecentRequestsByIPParams struct {
	Ip      *string         `json:"ip"`
	Column2 pgtype.Interval `json:"column_2"`
}

func (q *Queries) CountRecentRequestsByIP(ctx context.Context, arg CountRecentRequestsByIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentRequestsByIP, arg.Ip, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccessRequest = `-- name: CreateAccessRequest :one
INSERT INTO access_requests (name, email, reason, ip, user_agent)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, reason, status, magic_token_hash, magic_expires_at, magic_used_at, session_hash, session_expires_at, ip, user_agent, telegram_msg_id, created_at, decided_at, decided_by
`

type CreateAccessRequestParams struct {
	Name      string  `json:"name"`
	Email     string  `json:"email"`
	Reason    string  `json:"reason"`
	Ip        *string `json:"ip"`
	UserAgent *string `json:"user_agent"`
}

func (q *Queries) CreateAccessRequest(ctx context.Context, arg CreateAccessRequestParams) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, createAccessRequest,
		arg.Name,
		arg.Email,
		arg.Reason,
		arg.Ip,
		arg.UserAgent,
	)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Reason,
		&i.Status,
		&i.MagicTokenHash,
		&i.MagicExpiresAt,
		&i.MagicUsedAt,
		&i.SessionHash,
		&i.SessionExpiresAt,
		&i.Ip,
		&i.UserAgent,
		&i.TelegramMsgID,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
	)
	return i, err
}

const denyAccessRequest = `-- name: DenyAccessRequest :one
UPDATE access_requests
SET status = 'denied', decided_at = NOW(), decided_by = $2
WHERE id = $1
RETURNING id, name, email, reason, status, magic_token_hash, magic_expires_at, magic_used_at, session_hash, session_expires_at, ip, user_agent, telegram_msg_id, created_at, decided_at, decided_by
`

type DenyAccessRequestParams struct {
	ID        uuid.UUID `json:"id"`
	DecidedBy *string   `json:"decided_by"`
}

func (q *Queries) DenyAccessRequest(ctx context.Context, arg DenyAccessRequestParams) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, denyAccessRequest, arg.ID, arg.DecidedBy)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Reason,
		&i.Status,
		&i.MagicTokenHash,
		&i.MagicExpiresAt,
		&i.MagicUsedAt,
		&i.SessionHash,
		&i.SessionExpiresAt,
		&i.Ip,
		&i.UserAgent,
		&i.TelegramMsgID,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
	)
	return i, err
}

const getAccessRequestByID = `-- name: GetAccessRequestByID :one
SELECT id, name, email, reason, status, magic_token_hash, magic_expires_at, magic_used_at, session_hash, session_expires_at, ip, user_agent, telegram_msg_id, created_at, decided_at, decided_by FROM access_requests WHERE id = $1
`

func (q *Queries) GetAccessRequestByID(ctx context.Context, id uuid.UUID) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, getAccessRequestByID, id)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Reason,
		&i.Status,
		&i.MagicTokenHash,
		&i.MagicExpiresAt,
		&i.MagicUsedAt,
		&i.SessionHash,
		&i.SessionExpiresAt,
		&i.Ip,
		&i.UserAgent,
		&i.TelegramMsgID,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
	)
	return i, err
}

const getActiveAccessBySession = `-- name: GetActiveAccessBySession :one
SELECT id, name, email, reason, status, magic_token_hash, magic_expires_at, magic_used_at, session_hash, session_expires_at, ip, user_agent, telegram_msg_id, created_at, decided_at, decided_by FROM access_requests
WHERE session_hash = $1
  AND status = 'approved'
  AND session_expires_at > NOW()
`

func (q *Queries) GetActiveAccessBySession(ctx context.Context, sessionHash *string) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, getActiveAccessBySession, sessionHash)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Reason,
		&i.Status,
		&i.MagicTokenHash,
		&i.MagicExpiresAt,
		&i.MagicUsedAt,
		&i.SessionHash,
		&i.SessionExpiresAt,
		&i.Ip,
		&i.UserAgent,
		&i.TelegramMsgID,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
	)
	return i, err
}

const getApprovedByMagicHash = `-- name: GetApprovedByMagicHash :one
SELECT id, name, email, reason, status, magic_token_hash, magic_expires_at, magic_used_at, session_hash, session_expires_at, ip, user_agent, telegram_msg_id, created_at, decided_at, decided_by FROM access_requests
WHERE magic_token_hash = $1
  AND status = 'approved'
  AND magic_used_at IS NULL
  AND magic_expires_at > NOW()
`

func (q *Queries) GetApprovedByMagicHash(ctx context.Context, magicTokenHash *string) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, getApprovedByMagicHash, magicTokenHash)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Reason,
		&i.Status,
		&i.MagicTokenHash,
		&i.MagicExpiresAt,
		&i.MagicUsedAt,
		&i.SessionHash,
		&i.SessionExpiresAt,
		&i.Ip,
		&i.UserAgent,
		&i.TelegramMsgID,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
	)
	return i, err
}

const listAccessRequests = `-- name: ListAccessRequests :many
SELECT id, name, email, reason, status, magic_token_hash, magic_expires_at, magic_used_at, session_hash, session_expires_at, ip, user_agent, telegram_msg_id, created_at, decided_at, decided_by FROM access_requests
WHERE ($3::access_status IS NULL OR status = $3::access_status)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAccessRequestsParams struct {
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
	Status *AccessStatus `json:"status"`
}

func (q *Queries) ListAccessRequests(ctx context.Context, arg ListAccessRequestsParams) ([]AccessRequest, error) {
	rows, err := q.db.Query(ctx, listAccessRequests, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessRequest
	for rows.Next() {
		var i AccessRequest
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Reason,
			&i.Status,
			&i.MagicTokenHash,
			&i.MagicExpiresAt,
			&i.MagicUsedAt,
			&i.SessionHash,
			&i.SessionExpiresAt,
			&i.Ip,
			&i.UserAgent,
			&i.TelegramMsgID,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.DecidedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAccessRequest = `-- name: RevokeAccessRequest :one
UPDATE access_requests
SET status = 'revoked', session_hash = NULL, session_expires_at = NULL
WHERE id = $1
RETURNING id, name, email, reason, status, magic_token_hash, magic_expires_at, magic_used_at, session_hash, session_expires_at, ip, user_agent, telegram_msg_id, created_at, decided_at, decided_by
`

func (q *Queries) RevokeAccessRequest(ctx context.Context, id uuid.UUID) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, revokeAccessRequest, id)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Reason,
		&i.Status,
		&i.MagicTokenHash,
		&i.MagicExpiresAt,
		&i.MagicUsedAt,
		&i.SessionHash,
		&i.SessionExpiresAt,
		&i.Ip,
		&i.UserAgent,
		&i.TelegramMsgID,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
	)
	return i, err
}

const setAccessTelegramMsgID = `-- name: SetAccessTelegramMsgID :exec
UPDATE access_requests SET telegram_msg_id = $2 WHERE id = $1
`

type SetAccessTelegramMsgIDParams struct {
	ID            uuid.UUID `json:"id"`
	TelegramMsgID *int64    `json:"telegram_msg_id"`
}

func (q *Queries) SetAccessTelegramMsgID(ctx context.Context, arg SetAccessTelegramMsgIDParams) error {
	_, err := q.db.Exec(ctx, setAccessTelegramMsgID, arg.ID, arg.TelegramMsgID)
	return err
}
