// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (post_id, r2_key, url, mime_type, size_bytes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, post_id, r2_key, url, mime_type, size_bytes, uploaded_at
`

type CreateMediaParams struct {
	PostID    *uuid.UUID `json:"post_id"`
	R2Key     string     `json:"r2_key"`
	Url       string     `json:"url"`
	MimeType  string     `json:"mime_type"`
	SizeBytes int64      `json:"size_bytes"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.PostID,
		arg.R2Key,
		arg.Url,
		arg.MimeType,
		arg.SizeBytes,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.R2Key,
		&i.Url,
		&i.MimeType,
		&i.SizeBytes,
		&i.UploadedAt,
	)
	return i, err
}

const deleteMediaByID = `-- name: DeleteMediaByID :exec
DELETE FROM media WHERE id = $1
`

func (q *Queries) DeleteMediaByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMediaByID, id)
	return err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, post_id, r2_key, url, mime_type, size_bytes, uploaded_at FROM media WHERE id = $1
`

func (q *Queries) GetMediaByID(ctx context.Context, id uuid.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.R2Key,
		&i.Url,
		&i.MimeType,
		&i.SizeBytes,
		&i.UploadedAt,
	)
	return i, err
}

const listMediaByPostSlug = `-- name: ListMediaByPostSlug :many
SELECT m.id, m.post_id, m.r2_key, m.url, m.mime_type, m.size_bytes, m.uploaded_at FROM media m
JOIN posts p ON p.id = m.post_id
WHERE p.slug = $1
ORDER BY m.uploaded_at DESC
`

func (q *Queries) ListMediaByPostSlug(ctx context.Context, slug string) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMediaByPostSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.R2Key,
			&i.Url,
			&i.MimeType,
			&i.SizeBytes,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaKeysByPostSlug = `-- name: ListMediaKeysByPostSlug :many
SELECT m.r2_key FROM media m
JOIN posts p ON p.id = m.post_id
WHERE p.slug = $1
`

func (q *Queries) ListMediaKeysByPostSlug(ctx context.Context, slug string) ([]string, error) {
	rows, err := q.db.Query(ctx, listMediaKeysByPostSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var r2_key string
		if err := rows.Scan(&r2_key); err != nil {
			return nil, err
		}
		items = append(items, r2_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
