// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessStatus string

const (
	AccessStatusPending  AccessStatus = "pending"
	AccessStatusApproved AccessStatus = "approved"
	AccessStatusDenied   AccessStatus = "denied"
	AccessStatusRevoked  AccessStatus = "revoked"
)

func (e *AccessStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccessStatus(s)
	case string:
		*e = AccessStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccessStatus: %T", src)
	}
	return nil
}

type NullAccessStatus struct {
	AccessStatus AccessStatus `json:"access_status"`
	Valid        bool         `json:"valid"` // Valid is true if AccessStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccessStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccessStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccessStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccessStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccessStatus), nil
}

type PostType string

const (
	PostTypeWeekly   PostType = "weekly"
	PostTypeDaily    PostType = "daily"
	PostTypeDeepDive PostType = "deep-dive"
	PostTypeTil      PostType = "til"
)

func (e *PostType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostType(s)
	case string:
		*e = PostType(s)
	default:
		return fmt.Errorf("unsupported scan type for PostType: %T", src)
	}
	return nil
}

type NullPostType struct {
	PostType PostType `json:"post_type"`
	Valid    bool     `json:"valid"` // Valid is true if PostType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostType) Scan(value interface{}) error {
	if value == nil {
		ns.PostType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostType), nil
}

type AccessRequest struct {
	ID               uuid.UUID          `json:"id"`
	Name             string             `json:"name"`
	Email            string             `json:"email"`
	Reason           string             `json:"reason"`
	Status           AccessStatus       `json:"status"`
	MagicTokenHash   *string            `json:"magic_token_hash"`
	MagicExpiresAt   pgtype.Timestamptz `json:"magic_expires_at"`
	MagicUsedAt      pgtype.Timestamptz `json:"magic_used_at"`
	SessionHash      *string            `json:"session_hash"`
	SessionExpiresAt pgtype.Timestamptz `json:"session_expires_at"`
	Ip               *string            `json:"ip"`
	UserAgent        *string            `json:"user_agent"`
	TelegramMsgID    *int64             `json:"telegram_msg_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	DecidedAt        pgtype.Timestamptz `json:"decided_at"`
	DecidedBy        *string            `json:"decided_by"`
}

type Medium struct {
	ID         uuid.UUID          `json:"id"`
	PostID     *uuid.UUID         `json:"post_id"`
	R2Key      string             `json:"r2_key"`
	Url        string             `json:"url"`
	MimeType   string             `json:"mime_type"`
	SizeBytes  int64              `json:"size_bytes"`
	UploadedAt pgtype.Timestamptz `json:"uploaded_at"`
}

type Now struct {
	ID        int32              `json:"id"`
	Body      string             `json:"body"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Post struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	Type        PostType           `json:"type"`
	Title       string             `json:"title"`
	Summary     string             `json:"summary"`
	Body        string             `json:"body"`
	Tags        []string           `json:"tags"`
	ReadingTime int32              `json:"reading_time"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PrivateProfile struct {
	ID               int32              `json:"id"`
	CvMarkdown       string             `json:"cv_markdown"`
	ProjectsMarkdown string             `json:"projects_markdown"`
	ContactMarkdown  string             `json:"contact_markdown"`
	ResumeUrl        *string            `json:"resume_url"`
	ReferencesJson   []byte             `json:"references_json"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Tags        []string           `json:"tags"`
	UrlLive     *string            `json:"url_live"`
	UrlRepo     *string            `json:"url_repo"`
	Featured    bool               `json:"featured"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
