// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: now.sql

package store

import (
	"context"
)

const getNow = `-- name: GetNow :one
SELECT id, body, updated_at FROM now WHERE id = 1
`

func (q *Queries) GetNow(ctx context.Context) (Now, error) {
	row := q.db.QueryRow(ctx, getNow)
	var i Now
	err := row.Scan(&i.ID, &i.Body, &i.UpdatedAt)
	return i, err
}

const updateNow = `-- name: UpdateNow :one
UPDATE now SET body = $1, updated_at = NOW() WHERE id = 1
RETURNING id, body, updated_at
`

func (q *Queries) UpdateNow(ctx context.Context, body string) (Now, error) {
	row := q.db.QueryRow(ctx, updateNow, body)
	var i Now
	err := row.Scan(&i.ID, &i.Body, &i.UpdatedAt)
	return i, err
}
