// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPublishedPosts = `-- name: CountPublishedPosts :one
SELECT COUNT(*)
FROM posts
WHERE published_at IS NOT NULL
  AND ($1::post_type IS NULL OR type = $1::post_type)
  AND ($2::text IS NULL OR $2::text = ANY(tags))
`

type CountPublishedPostsParams struct {
	Type *PostType `json:"type"`
	Tag  *string   `json:"tag"`
}

func (q *Queries) CountPublishedPosts(ctx context.Context, arg CountPublishedPostsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedPosts, arg.Type, arg.Tag)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (slug, type, title, summary, body, tags, reading_time)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, slug, type, title, summary, body, tags, reading_time, published_at, created_at, updated_at
`

type CreatePostParams struct {
	Slug        string   `json:"slug"`
	Type        PostType `json:"type"`
	Title       []byte   `json:"title"`
	Summary     []byte   `json:"summary"`
	Body        []byte   `json:"body"`
	Tags        []string `json:"tags"`
	ReadingTime int32    `json:"reading_time"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.Slug,
		arg.Type,
		arg.Title,
		arg.Summary,
		arg.Body,
		arg.Tags,
		arg.ReadingTime,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Type,
		&i.Title,
		&i.Summary,
		&i.Body,
		&i.Tags,
		&i.ReadingTime,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE slug = $1
`

func (q *Queries) DeletePost(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deletePost, slug)
	return err
}

const getPostBySlug = `-- name: GetPostBySlug :one
SELECT id, slug, type, title, summary, body, tags, reading_time, published_at, created_at, updated_at FROM posts WHERE slug = $1
`

func (q *Queries) GetPostBySlug(ctx context.Context, slug string) (Post, error) {
	row := q.db.QueryRow(ctx, getPostBySlug, slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Type,
		&i.Title,
		&i.Summary,
		&i.Body,
		&i.Tags,
		&i.ReadingTime,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedPostBySlug = `-- name: GetPublishedPostBySlug :one
SELECT id, slug, type, title, summary, body, tags, reading_time, published_at, created_at, updated_at FROM posts
WHERE slug = $1 AND published_at IS NOT NULL
`

func (q *Queries) GetPublishedPostBySlug(ctx context.Context, slug string) (Post, error) {
	row := q.db.QueryRow(ctx, getPublishedPostBySlug, slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Type,
		&i.Title,
		&i.Summary,
		&i.Body,
		&i.Tags,
		&i.ReadingTime,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPostsAdmin = `-- name: ListAllPostsAdmin :many
SELECT id, slug, type, title, summary, tags, reading_time, published_at, created_at, updated_at
FROM posts
ORDER BY created_at DESC
`

type ListAllPostsAdminRow struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	Type        PostType           `json:"type"`
	Title       []byte             `json:"title"`
	Summary     []byte             `json:"summary"`
	Tags        []string           `json:"tags"`
	ReadingTime int32              `json:"reading_time"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAllPostsAdmin(ctx context.Context) ([]ListAllPostsAdminRow, error) {
	rows, err := q.db.Query(ctx, listAllPostsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllPostsAdminRow
	for rows.Next() {
		var i ListAllPostsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Type,
			&i.Title,
			&i.Summary,
			&i.Tags,
			&i.ReadingTime,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPosts = `-- name: ListPublishedPosts :many
SELECT id, slug, type, title, summary, tags, reading_time, published_at, created_at, updated_at
FROM posts
WHERE published_at IS NOT NULL
  AND ($3::post_type IS NULL OR type = $3::post_type)
  AND ($4::text IS NULL OR $4::text = ANY(tags))
ORDER BY published_at DESC
LIMIT $1 OFFSET $2
`

type ListPublishedPostsParams struct {
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
	Type   *PostType `json:"type"`
	Tag    *string   `json:"tag"`
}

type ListPublishedPostsRow struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	Type        PostType           `json:"type"`
	Title       []byte             `json:"title"`
	Summary     []byte             `json:"summary"`
	Tags        []string           `json:"tags"`
	ReadingTime int32              `json:"reading_time"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPublishedPosts(ctx context.Context, arg ListPublishedPostsParams) ([]ListPublishedPostsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPosts,
		arg.Limit,
		arg.Offset,
		arg.Type,
		arg.Tag,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPostsRow
	for rows.Next() {
		var i ListPublishedPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Type,
			&i.Title,
			&i.Summary,
			&i.Tags,
			&i.ReadingTime,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPublished = `-- name: ListRecentPublished :many
SELECT id, slug, type, title, summary, tags, reading_time, published_at, created_at, updated_at
FROM posts
WHERE published_at IS NOT NULL
ORDER BY published_at DESC
LIMIT $1
`

type ListRecentPublishedRow struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	Type        PostType           `json:"type"`
	Title       []byte             `json:"title"`
	Summary     []byte             `json:"summary"`
	Tags        []string           `json:"tags"`
	ReadingTime int32              `json:"reading_time"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListRecentPublished(ctx context.Context, limit int32) ([]ListRecentPublishedRow, error) {
	rows, err := q.db.Query(ctx, listRecentPublished, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentPublishedRow
	for rows.Next() {
		var i ListRecentPublishedRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Type,
			&i.Title,
			&i.Summary,
			&i.Tags,
			&i.ReadingTime,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishPost = `-- name: PublishPost :one
UPDATE posts
SET published_at = NOW(), updated_at = NOW()
WHERE slug = $1
RETURNING id, slug, type, title, summary, body, tags, reading_time, published_at, created_at, updated_at
`

func (q *Queries) PublishPost(ctx context.Context, slug string) (Post, error) {
	row := q.db.QueryRow(ctx, publishPost, slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Type,
		&i.Title,
		&i.Summary,
		&i.Body,
		&i.Tags,
		&i.ReadingTime,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPublishedAt = `-- name: SetPublishedAt :one
UPDATE posts
SET published_at = $2, updated_at = NOW()
WHERE slug = $1
RETURNING id, slug, type, title, summary, body, tags, reading_time, published_at, created_at, updated_at
`

type SetPublishedAtParams struct {
	Slug        string             `json:"slug"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

// Publish with an explicit timestamp (used for backdating a post).
func (q *Queries) SetPublishedAt(ctx context.Context, arg SetPublishedAtParams) (Post, error) {
	row := q.db.QueryRow(ctx, setPublishedAt, arg.Slug, arg.PublishedAt)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Type,
		&i.Title,
		&i.Summary,
		&i.Body,
		&i.Tags,
		&i.ReadingTime,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tagCounts = `-- name: TagCounts :many
SELECT unnest(tags) AS tag, COUNT(*) AS count
FROM posts
WHERE published_at IS NOT NULL
GROUP BY tag
ORDER BY count DESC, tag ASC
`

type TagCountsRow struct {
	Tag   interface{} `json:"tag"`
	Count int64       `json:"count"`
}

func (q *Queries) TagCounts(ctx context.Context) ([]TagCountsRow, error) {
	rows, err := q.db.Query(ctx, tagCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TagCountsRow
	for rows.Next() {
		var i TagCountsRow
		if err := rows.Scan(&i.Tag, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unpublishPost = `-- name: UnpublishPost :one
UPDATE posts
SET published_at = NULL, updated_at = NOW()
WHERE slug = $1
RETURNING id, slug, type, title, summary, body, tags, reading_time, published_at, created_at, updated_at
`

func (q *Queries) UnpublishPost(ctx context.Context, slug string) (Post, error) {
	row := q.db.QueryRow(ctx, unpublishPost, slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Type,
		&i.Title,
		&i.Summary,
		&i.Body,
		&i.Tags,
		&i.ReadingTime,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET type = $2, title = $3, summary = $4, body = $5, tags = $6, reading_time = $7, updated_at = NOW()
WHERE slug = $1
RETURNING id, slug, type, title, summary, body, tags, reading_time, published_at, created_at, updated_at
`

type UpdatePostParams struct {
	Slug        string   `json:"slug"`
	Type        PostType `json:"type"`
	Title       []byte   `json:"title"`
	Summary     []byte   `json:"summary"`
	Body        []byte   `json:"body"`
	Tags        []string `json:"tags"`
	ReadingTime int32    `json:"reading_time"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.Slug,
		arg.Type,
		arg.Title,
		arg.Summary,
		arg.Body,
		arg.Tags,
		arg.ReadingTime,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Type,
		&i.Title,
		&i.Summary,
		&i.Body,
		&i.Tags,
		&i.ReadingTime,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
