// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: private_profile.sql

package store

import (
	"context"
)

const getPrivateProfile = `-- name: GetPrivateProfile :one
SELECT id, cv_markdown, projects_markdown, contact_markdown, resume_url, references_json, updated_at FROM private_profile WHERE id = 1
`

func (q *Queries) GetPrivateProfile(ctx context.Context) (PrivateProfile, error) {
	row := q.db.QueryRow(ctx, getPrivateProfile)
	var i PrivateProfile
	err := row.Scan(
		&i.ID,
		&i.CvMarkdown,
		&i.ProjectsMarkdown,
		&i.ContactMarkdown,
		&i.ResumeUrl,
		&i.ReferencesJson,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePrivateProfile = `-- name: UpdatePrivateProfile :one
UPDATE private_profile
SET cv_markdown = $1,
    projects_markdown = $2,
    contact_markdown = $3,
    resume_url = $4,
    references_json = $5,
    updated_at = NOW()
WHERE id = 1
RETURNING id, cv_markdown, projects_markdown, contact_markdown, resume_url, references_json, updated_at
`

type UpdatePrivateProfileParams struct {
	CvMarkdown       string `json:"cv_markdown"`
	ProjectsMarkdown string `json:"projects_markdown"`
	ContactMarkdown  string `json:"contact_markdown"`
	ResumeUrl        []byte `json:"resume_url"`
	ReferencesJson   []byte `json:"references_json"`
}

func (q *Queries) UpdatePrivateProfile(ctx context.Context, arg UpdatePrivateProfileParams) (PrivateProfile, error) {
	row := q.db.QueryRow(ctx, updatePrivateProfile,
		arg.CvMarkdown,
		arg.ProjectsMarkdown,
		arg.ContactMarkdown,
		arg.ResumeUrl,
		arg.ReferencesJson,
	)
	var i PrivateProfile
	err := row.Scan(
		&i.ID,
		&i.CvMarkdown,
		&i.ProjectsMarkdown,
		&i.ContactMarkdown,
		&i.ResumeUrl,
		&i.ReferencesJson,
		&i.UpdatedAt,
	)
	return i, err
}
