// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (slug, title, description, tags, url_live, url_repo, featured, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, slug, title, description, tags, url_live, url_repo, featured, sort_order, created_at
`

type CreateProjectParams struct {
	Slug        string   `json:"slug"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Tags        []string `json:"tags"`
	UrlLive     *string  `json:"url_live"`
	UrlRepo     *string  `json:"url_repo"`
	Featured    bool     `json:"featured"`
	SortOrder   int32    `json:"sort_order"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Tags,
		arg.UrlLive,
		arg.UrlRepo,
		arg.Featured,
		arg.SortOrder,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.UrlLive,
		&i.UrlRepo,
		&i.Featured,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE slug = $1
`

func (q *Queries) DeleteProject(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deleteProject, slug)
	return err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, slug, title, description, tags, url_live, url_repo, featured, sort_order, created_at FROM projects WHERE slug = $1
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.UrlLive,
		&i.UrlRepo,
		&i.Featured,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, slug, title, description, tags, url_live, url_repo, featured, sort_order, created_at FROM projects
ORDER BY featured DESC, sort_order ASC, created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.UrlLive,
			&i.UrlRepo,
			&i.Featured,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectSortOrder = `-- name: SetProjectSortOrder :exec
UPDATE projects SET sort_order = $2 WHERE id = $1
`

type SetProjectSortOrderParams struct {
	ID        uuid.UUID `json:"id"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) SetProjectSortOrder(ctx context.Context, arg SetProjectSortOrderParams) error {
	_, err := q.db.Exec(ctx, setProjectSortOrder, arg.ID, arg.SortOrder)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET title = $2, description = $3, tags = $4, url_live = $5, url_repo = $6, featured = $7, sort_order = $8
WHERE slug = $1
RETURNING id, slug, title, description, tags, url_live, url_repo, featured, sort_order, created_at
`

type UpdateProjectParams struct {
	Slug        string   `json:"slug"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Tags        []string `json:"tags"`
	UrlLive     *string  `json:"url_live"`
	UrlRepo     *string  `json:"url_repo"`
	Featured    bool     `json:"featured"`
	SortOrder   int32    `json:"sort_order"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Tags,
		arg.UrlLive,
		arg.UrlRepo,
		arg.Featured,
		arg.SortOrder,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.UrlLive,
		&i.UrlRepo,
		&i.Featured,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
